/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author jairus
 */
public class logIn extends javax.swing.JFrame {

    ImageIcon image = new ImageIcon("C:\\Users\\jairus\\Documents\\GitHub\\First-Year-Projects\\Inventory-System\\src\\main\\java\\resources\\logoSmall.png");

    /**
     * Creates new form logIn
     */
    public logIn() {
        initComponents();
        setIconImage(image.getImage());
        passField.setEchoChar('•');
        //userField.setEchoChar((char)0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        forgotUser = new javax.swing.JButton();
        forgotPass = new javax.swing.JButton();
        License = new javax.swing.JButton();
        signInBtn = new settings.RoundedButtons();
        showPass = new settings.JCheckBoxCustom();
        textField = new settings.TextField();
        passField = new settings.PasswordField();
        signedIn = new settings.Combobox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setMinimumSize(new java.awt.Dimension(1080, 750));
        setPreferredSize(new java.awt.Dimension(1080, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(15, 106, 191));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Log In to your Account");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 150, 550, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\jairus\\Documents\\GitHub\\First-Year-Projects\\Inventory-System\\src\\main\\java\\resources\\logInBg.png")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -10, 670, 770);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(420, 0, 670, 750);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        userIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\jairus\\Documents\\GitHub\\First-Year-Projects\\Inventory-System\\src\\main\\java\\resources\\logInUser.png")); // NOI18N
        jPanel1.add(userIcon);
        userIcon.setBounds(150, 110, 120, 120);

        forgotUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        forgotUser.setForeground(new java.awt.Color(153, 153, 153));
        forgotUser.setText("Forgot Username?");
        forgotUser.setBorderPainted(false);
        forgotUser.setContentAreaFilled(false);
        forgotUser.setFocusPainted(false);
        forgotUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotUserActionPerformed(evt);
            }
        });
        jPanel1.add(forgotUser);
        forgotUser.setBounds(250, 340, 140, 26);

        forgotPass.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        forgotPass.setForeground(new java.awt.Color(153, 153, 153));
        forgotPass.setText("Forgot Password?");
        forgotPass.setBorderPainted(false);
        forgotPass.setContentAreaFilled(false);
        forgotPass.setFocusPainted(false);
        forgotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPassActionPerformed(evt);
            }
        });
        jPanel1.add(forgotPass);
        forgotPass.setBounds(250, 440, 140, 26);

        License.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        License.setForeground(new java.awt.Color(153, 153, 153));
        License.setText("@2024 Mark-It!");
        License.setBorderPainted(false);
        License.setContentAreaFilled(false);
        License.setFocusPainted(false);
        License.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseActionPerformed(evt);
            }
        });
        jPanel1.add(License);
        License.setBounds(140, 720, 140, 26);

        signInBtn.setForeground(new java.awt.Color(40, 72, 172));
        signInBtn.setText("Log In");
        signInBtn.setBorderColor(new java.awt.Color(15, 106, 191));
        signInBtn.setBorderPainted(false);
        signInBtn.setColorClick(new java.awt.Color(153, 153, 153));
        signInBtn.setColorOver(new java.awt.Color(204, 204, 204));
        signInBtn.setFocusPainted(false);
        signInBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel1.add(signInBtn);
        signInBtn.setBounds(130, 640, 160, 40);

        showPass.setForeground(new java.awt.Color(153, 153, 153));
        showPass.setText(" Show Password");
        showPass.setFocusPainted(false);
        showPass.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        jPanel1.add(showPass);
        showPass.setBounds(40, 443, 160, 23);

        textField.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel1.add(textField);
        textField.setBounds(40, 280, 330, 49);

        passField.setSelectionColor(new java.awt.Color(204, 204, 204));
        jPanel1.add(passField);
        passField.setBounds(40, 380, 330, 49);

        signedIn.setMaximumRowCount(3);
        signedIn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Supervisor", "Administrator" }));
        signedIn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        signedIn.setLabelText("Log in as");
        signedIn.setOpaque(false);
        jPanel1.add(signedIn);
        signedIn.setBounds(40, 510, 330, 45);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -40, 420, 790);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forgotUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotUserActionPerformed

    private void LicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicenseActionPerformed

    private void forgotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotPassActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
 
        if(showPass.isSelected()){
            passField.setEchoChar((char) 0);
        } else passField.setEchoChar('•');
        
    }//GEN-LAST:event_showPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new logIn().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton License;
    private javax.swing.JButton forgotPass;
    private javax.swing.JButton forgotUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private settings.PasswordField passField;
    private settings.JCheckBoxCustom showPass;
    private settings.RoundedButtons signInBtn;
    private settings.Combobox signedIn;
    private settings.TextField textField;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
